language: rust
rust:
  - stable

os:
  - linux
  - windows
  - osx

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo build --no-default-features --verbose
  - cargo test --no-default-features --verbose

cache: cargo
